SRH_Radio/config/routes.rb
Rails.application.routes.draw do
  resources :podcasts

end

SRH_Radio/app/models/podcast.rb
class Podcast < ActiveRecord::Base
end

SRH_Radio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

SRH_Radio/app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  respond_to :html, :xml, :json, :js

 def show
   @product = Podcast.find(params[:id])

   respond_with(@product) do |format|
     format.js  { render :json => @product, :callback => params[:callback] }
   end

 end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:podcastName, :category, :subcategory, :description)
    end
end

SRH_Radio/app/helpers/application_helper.rb
module ApplicationHelper
end

SRH_Radio/app/helpers/podcasts_helper.rb
module PodcastsHelper
end

SRH_Radio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SRHRadio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

SRH_Radio/app/views/podcasts/_form.html.erb
<%= form_for(@podcast) do |f| %>
  <% if @podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% @podcast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :podcastName %><br>
    <%= f.text_field :podcastName %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br>
    <%= f.text_field :subcategory %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SRH_Radio/app/views/podcasts/edit.html.erb
<h1>Editing podcast</h1>

<%= render 'form' %>

<%= link_to 'Show', @podcast %> |
<%= link_to 'Back', podcasts_path %>

SRH_Radio/app/views/podcasts/index.html.erb
<h1>Listing podcasts</h1>

<table>
  <thead>
    <tr>
      <th>Podcastname</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @podcasts.each do |podcast| %>
      <tr>
        <td><%= podcast.podcastName %></td>
        <td><%= podcast.category %></td>
        <td><%= podcast.subcategory %></td>
        <td><%= podcast.description %></td>
        <td><%= link_to 'Show', podcast %></td>
        <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>
        <td><%= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Podcast', new_podcast_path %>

SRH_Radio/app/views/podcasts/new.html.erb
<h1>New podcast</h1>

<%= render 'form' %>

<%= link_to 'Back', podcasts_path %>

SRH_Radio/app/views/podcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Podcastname:</strong>
  <%= @podcast.podcastName %>
</p>

<p>
  <strong>Category:</strong>
  <%= @podcast.category %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @podcast.subcategory %>
</p>

<p>
  <strong>Description:</strong>
  <%= @podcast.description %>
</p>

<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>